{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fleetlock.serviceAccountName" . }}
  labels: {{- include "fleetlock.labels" . | nindent 4 }}
{{- with .Values.serviceAccount.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
