kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ printf "system:%s" (include "hcloud-cloud-controller-manager.serviceAccountName" .) }}
  labels: {{- include "hcloud-cloud-controller-manager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
  # name: {{ include "hcloud-cloud-controller-manager.serviceAccountName" . }}
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ include "hcloud-cloud-controller-manager.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
