{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hcloud-cloud-controller-manager.serviceAccountName" . }}
  labels: {{- include "hcloud-cloud-controller-manager.labels" . | nindent 4 }}
{{- with .Values.serviceAccount.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
